attachments:
  base-path: /tmp
spring:
  application:
    name: accounts-app
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
